spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-72db1xlk.sql.tencentcdb.com:22462/nblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&autoReconnectForPools=true
    username: root
    password: MJBkh.HrDgd9-j9
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: 49.232.66.58
    port: 6379
    password: 131214

  aop:
    auto: true
    proxy-target-class: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zxqax.nblog.dao
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 260         