spring:
  datasource:
    url: jdbc:mysql://your_host:your_post/your_dataset?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&autoReconnectForPools=true
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: your_host
    port: your_post
    password: your_password

  aop:
    auto: true
    proxy-target-class: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zxqax.nblog.dao
  configuration:
    map-underscore-to-camel-case: true

server:
  port: your_post         